export const GET_LOADS_REQUEST = 'GET_LOADS/REQUEST'
export const GET_LOADS_SUCCESS = 'GET_LOADS/SUCCESS'
export const GET_LOADS_FAILURE = 'GET_LOADS/FAILURE'

export default { GET_LOADS_REQUEST, GET_LOADS_SUCCESS, GET_LOADS_FAILURE }
