export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER/SUCCESS'
export const GET_USER_FAILURE = 'GET_USER/FAILURE'

export default { GET_USER, GET_USER_SUCCESS, GET_USER_FAILURE }
