export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER/SUCCESS'
export const GET_USER_FAILURE = 'GET_USER/FAILURE'

export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN/SUCCESS'
export const UPDATE_TOKEN_FAILURE = 'UPDATE_TOKEN/FAILURE'

export default {
  GET_USER,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  UPDATE_TOKEN,
  UPDATE_TOKEN_SUCCESS,
  UPDATE_TOKEN_FAILURE
}
