export const LOGIN_REQUEST = 'LOGIN/REQUEST'
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS'
export const LOGIN_FAILURE = 'LOGIN/FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
}
