export const GET_LOAD_BY_ID_REQUEST = 'GET_LOAD_BY_ID/REQUEST'
export const GET_LOAD_BY_ID_SUCCESS = 'GET_LOAD_BY_ID/SUCCESS'
export const GET_LOAD_BY_ID_FAILURE = 'GET_LOAD_BY_ID/FAILURE'

export default {
  GET_LOAD_BY_ID_REQUEST,
  GET_LOAD_BY_ID_SUCCESS,
  GET_LOAD_BY_ID_FAILURE
}
